version: "2"
services:
  api:
    build: .
    volumes:
      - .:/go/src/netpro/testing-nextalent
    ports:
      - 8080:8080 # API server
    depends_on:
      - postgres
    networks:
      default:
        priority: 1
  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: testing
      POSTGRES_USER: root
    ports:
      - 5432:5432

networks:
  default:
    driver: bridge
  services:
    driver: bridge